#ifndef ENEMIES_H
#define ENEMIES_H

#include "util.h"

enum Enemy {
  ENEMY_ENEMYTEST1,  // ADD NEW ENEMIES HERE
  ENEMY_ENEMYTEST2,
  ENEMY_SIMPLESHOTGUN_TOP_LEFT,
  ENEMY_SIMPLESHOTGUN_TOP_RIGHT,
  ENEMY_TANKYBANG_UP_DOWN,
  ENEMY_SIMPLESHOTGUN_MID_LEFT_UP,
  ENEMY_SIMPLESHOTGUN_MID_RIGHT_UP,
  ENEMY_WAVE1BASIC,
  ENEMY_DIVER,
  ENEMY_LARGE_SLOW_LEFTTORIGHT,
  ENEMY_LARGE_SLOW_RIGHTTOLEFT,
  ENEMY_small_fast_RIGHTTOLEFT,
  ENEMY_small_fast_LEFTTORIGHT,
  ENEMY_small_fast_TOPDOWNTOLEFT,
  ENEMY_small_fast_TOPDOWNTORIGHT,
};

class EntityEnemy;
class UID;

namespace Enemies {
extern EntityEnemy* spawn(Enemy enemy, UID id, const QPointF& loc);
}

#endif  // ENEMIES_H
