#include "texture.h"
#include <QPixmap>

namespace Textures {
const QPixmap getTexture(Texture texture) {
  switch (texture) {
    case TEXTURE_BULLET_ROUND_RED:
      return {"assets/textures/bullets/round/red.png"};
    case TEXTURE_BULLET_ROUND_ORANGE:
      return {"assets/textures/bullets/round/orange.png"};
    case TEXTURE_BULLET_ROUND_YELLOW:
      return {"assets/textures/bullets/round/yellow.png"};
    case TEXTURE_BULLET_ROUND_GREEN:
      return {"assets/textures/bullets/round/green.png"};
    case TEXTURE_BULLET_ROUND_AQUA:
      return {"assets/textures/bullets/round/aqua.png"};
    case TEXTURE_BULLET_ROUND_BLUE:
      return {"assets/textures/bullets/round/blue.png"};
    case TEXTURE_BULLET_ROUND_PURPLE:
      return {"assets/textures/bullets/round/purple.png"};
    case TEXTURE_BULLET_ROUND_MAGENTA:
      return {"assets/textures/bullets/round/magenta.png"};
    case TEXTURE_BULLET_ELLIPSE_RED:
      return {"assets/textures/bullets/ellipse/red.png"};
    case TEXTURE_BULLET_ELLIPSE_ORANGE:
      return {"assets/textures/bullets/ellipse/orange.png"};
    case TEXTURE_BULLET_ELLIPSE_YELLOW:
      return {"assets/textures/bullets/ellipse/yellow.png"};
    case TEXTURE_BULLET_ELLIPSE_GREEN:
      return {"assets/textures/bullets/ellipse/green.png"};
    case TEXTURE_BULLET_ELLIPSE_AQUA:
      return {"assets/textures/bullets/ellipse/aqua.png"};
    case TEXTURE_BULLET_ELLIPSE_BLUE:
      return {"assets/textures/bullets/ellipse/blue.png"};
    case TEXTURE_BULLET_ELLIPSE_PURPLE:
      return {"assets/textures/bullets/ellipse/purple.png"};
    case TEXTURE_BULLET_ELLIPSE_MAGENTA:
      return {"assets/textures/bullets/ellipse/magenta.png"};
    case TEXTURE_BULLET_ARROW_RED:
      return {"assets/textures/bullets/arrow/red.png"};
    case TEXTURE_BULLET_ARROW_ORANGE:
      return {"assets/textures/bullets/arrow/orange.png"};
    case TEXTURE_BULLET_ARROW_YELLOW:
      return {"assets/textures/bullets/arrow/yellow.png"};
    case TEXTURE_BULLET_ARROW_GREEN:
      return {"assets/textures/bullets/arrow/green.png"};
    case TEXTURE_BULLET_ARROW_AQUA:
      return {"assets/textures/bullets/arrow/aqua.png"};
    case TEXTURE_BULLET_ARROW_BLUE:
      return {"assets/textures/bullets/arrow/blue.png"};
    case TEXTURE_BULLET_ARROW_PURPLE:
      return {"assets/textures/bullets/arrow/purple.png"};
    case TEXTURE_BULLET_ARROW_MAGENTA:
      return {"assets/textures/bullets/arrow/magenta.png"};
    case TEXTURE_BULLET_STAR_RED:
      return {"assets/textures/bullets/star/red.png"};
    case TEXTURE_BULLET_STAR_ORANGE:
      return {"assets/textures/bullets/star/orange.png"};
    case TEXTURE_BULLET_STAR_YELLOW:
      return {"assets/textures/bullets/star/yellow.png"};
    case TEXTURE_BULLET_STAR_GREEN:
      return {"assets/textures/bullets/star/green.png"};
    case TEXTURE_BULLET_STAR_AQUA:
      return {"assets/textures/bullets/star/aqua.png"};
    case TEXTURE_BULLET_STAR_BLUE:
      return {"assets/textures/bullets/star/blue.png"};
    case TEXTURE_BULLET_STAR_PURPLE:
      return {"assets/textures/bullets/star/purple.png"};
    case TEXTURE_BULLET_STAR_MAGENTA:
      return {"assets/textures/bullets/star/magenta.png"};
    case TEXTURE_BULLET_LAZER_RED:
      return {"assets/textures/bullets/lazer/red.png"};
    case TEXTURE_BULLET_LAZER_ORANGE:
      return {"assets/textures/bullets/lazer/orange.png"};
    case TEXTURE_BULLET_LAZER_YELLOW:
      return {"assets/textures/bullets/lazer/yellow.png"};
    case TEXTURE_BULLET_LAZER_GREEN:
      return {"assets/textures/bullets/lazer/green.png"};
    case TEXTURE_BULLET_LAZER_AQUA:
      return {"assets/textures/bullets/lazer/aqua.png"};
    case TEXTURE_BULLET_LAZER_BLUE:
      return {"assets/textures/bullets/lazer/blue.png"};
    case TEXTURE_BULLET_LAZER_PURPLE:
      return {"assets/textures/bullets/LAZER/purple.png"};
    case TEXTURE_BULLET_LAZER_MAGENTA:
      return {"assets/textures/bullets/lazer/magenta.png"};
    case TEXTURE_COLLECTABLE_POWER:
      return {"assets/textures/collectables/power.png"};
    case TEXTURE_COLLECTABLE_POINTS:
      return {"assets/textures/collectables/points.png"};
    case TEXTURE_ENEMYTEMP:
      return {"assets/textures/enemies/enemy.png"};
    case TEXTURE_BACKGROUNDTEMP:
      return {"assets/textures/misc/background.png"};
    case TEXTURE_TITLETEMP:
      return {"assets/textures/misc/title.png"};
    case TEXTURE_PLAYER_HITBOX:
      return {"assets/textures/players/player_hitbox.png"};
    case TEXTURE_PYACHI:
      return {"assets/textures/players/pyachi.png"};
    case TEXTURE_AERON:
      return {"assets/textures/players/player.png"};
    case TEXTURE_PRYSMA:
      return {"assets/textures/players/player.png"};
    case TEXTURE_ANEKHANDA:
      return {"assets/textures/players/player.png"};
  }
}

int getZValue(Texture texture) {
  switch (texture) {
    case TEXTURE_BULLET_ROUND_RED:
    case TEXTURE_BULLET_ROUND_ORANGE:
    case TEXTURE_BULLET_ROUND_YELLOW:
    case TEXTURE_BULLET_ROUND_GREEN:
    case TEXTURE_BULLET_ROUND_AQUA:
    case TEXTURE_BULLET_ROUND_BLUE:
    case TEXTURE_BULLET_ROUND_PURPLE:
    case TEXTURE_BULLET_ROUND_MAGENTA:
    case TEXTURE_BULLET_ELLIPSE_RED:
    case TEXTURE_BULLET_ELLIPSE_ORANGE:
    case TEXTURE_BULLET_ELLIPSE_YELLOW:
    case TEXTURE_BULLET_ELLIPSE_GREEN:
    case TEXTURE_BULLET_ELLIPSE_AQUA:
    case TEXTURE_BULLET_ELLIPSE_BLUE:
    case TEXTURE_BULLET_ELLIPSE_PURPLE:
    case TEXTURE_BULLET_ELLIPSE_MAGENTA:
    case TEXTURE_BULLET_ARROW_RED:
    case TEXTURE_BULLET_ARROW_ORANGE:
    case TEXTURE_BULLET_ARROW_YELLOW:
    case TEXTURE_BULLET_ARROW_GREEN:
    case TEXTURE_BULLET_ARROW_AQUA:
    case TEXTURE_BULLET_ARROW_BLUE:
    case TEXTURE_BULLET_ARROW_PURPLE:
    case TEXTURE_BULLET_ARROW_MAGENTA:
    case TEXTURE_BULLET_STAR_RED:
    case TEXTURE_BULLET_STAR_ORANGE:
    case TEXTURE_BULLET_STAR_YELLOW:
    case TEXTURE_BULLET_STAR_GREEN:
    case TEXTURE_BULLET_STAR_AQUA:
    case TEXTURE_BULLET_STAR_BLUE:
    case TEXTURE_BULLET_STAR_PURPLE:
    case TEXTURE_BULLET_STAR_MAGENTA:
    case TEXTURE_BULLET_LAZER_RED:
    case TEXTURE_BULLET_LAZER_ORANGE:
    case TEXTURE_BULLET_LAZER_YELLOW:
    case TEXTURE_BULLET_LAZER_GREEN:
    case TEXTURE_BULLET_LAZER_AQUA:
    case TEXTURE_BULLET_LAZER_BLUE:
    case TEXTURE_BULLET_LAZER_PURPLE:
    case TEXTURE_BULLET_LAZER_MAGENTA:
      return 1;
    case TEXTURE_COLLECTABLE_POWER:
    case TEXTURE_COLLECTABLE_POINTS:
      return 3;
    case TEXTURE_ENEMYTEMP:
      return 2;
    case TEXTURE_BACKGROUNDTEMP:
    case TEXTURE_TITLETEMP:
      return 5;
    case TEXTURE_PYACHI:
    case TEXTURE_AERON:
    case TEXTURE_PRYSMA:
    case TEXTURE_ANEKHANDA:
      return 4;
    case TEXTURE_PLAYER_HITBOX:
      return 0;
  }
}
}  // namespace Textures
