#ifndef PACKET_H
#define PACKET_H

#include <QByteArray>
#include <QStringList>

enum Header {
	// INWARD PACKETS
	PACKETPLAYINCONNECT,
	PACKETPLAYINDISCONNECT,
	PACKETPLAYINUPDATELOBBY,
	PACKETPLAYINSTARTGAME,
	PACKETPLAYINUPDATEPLAYER,
	PACKETPLAYINPLAYERDEATH,
	PACKETPLAYINPLAYERSPAWN,

	// OUTWARD PACKETS
	PACKETPLAYOUTUPDATELOBBY,
	PACKETPLAYOUTSTARTGAME,
	PACKETPLAYOUTUPDATEPLAYER,
	PACKETPLAYOUTPLAYERDEATH,
	PACKETPLAYOUTPLAYERSPAWN,
};

class Packet {
 public:
	Packet(const Header&, const QStringList& = QStringList());

	Header header;
	QStringList data;

	QByteArray encode() const;
	static QList<Packet> decode(const QByteArray&);
};
#endif  // PACKET_H
